import type { GameEvent } from './types';

export const TOTAL_DAYS = 10;
export const QUESTIONS_PER_DAY = 3;
export const STARTING_MONEY = 3000;
export const RISK_LOSS_THRESHOLD = 75;
export const TOTAL_PLAYERS = 30;
export const SELECT_TOP = 5;

export const events: GameEvent[] = [
  {
    title: 'Un pedido enorme',
    text: 'Un cliente corporativo quiere comprar mucho más de lo que normalmente produces.',
    topic: 'Planeación, producción y negociación.',
    opts: [
      ['Aceptar y reorganizar producción', 'Ganancia media · crecimiento · riesgo moderado'],
      ['Negociar entregas por etapas', 'Ganancia menor · alta estabilidad'],
      ['Aceptar sin preguntar', 'Gran ganancia potencial · alto riesgo'],
    ],
    effects: [[320, 10, 7, 5, 3, 8], [220, 7, 5, 7, 6, 2], [650, 18, 10, 1, -5, 22]],
    riskyIndex: 2,
  },
  {
    title: 'Guerra de precios',
    text: 'Un competidor baja sus precios y amenaza con quitarte clientes.',
    topic: 'Marketing, estrategia competitiva y costos.',
    opts: [
      ['Guerra de precios', 'Mucho volumen · margen y liquidez en riesgo'],
      ['Mantener precio y vender valor', 'Margen y reputación · crecimiento moderado'],
      ['Descuento selectivo', 'Equilibrio entre ventas y margen'],
    ],
    effects: [[720, 20, 3, -2, -12, 25], [280, 8, 4, 6, 2, 1], [420, 11, 5, 3, 0, 5]],
    riskyIndex: 0,
  },
  {
    title: 'Conflicto de liderazgo',
    text: 'Dos mandos intermedios chocan y el equipo empieza a dividirse.',
    topic: 'Dirección, liderazgo, delegación y Fayol.',
    opts: [
      ['Delegar con autoridad y control', 'Cuesta tiempo · fortalece productividad'],
      ['Imponer resultados', 'Resultados rápidos · desgaste del equipo'],
      ['Negociar responsabilidades', 'Estabilidad · mejor coordinación'],
    ],
    effects: [[180, 6, 10, 2, 3, -1], [760, 24, 12, -8, -8, 28], [300, 8, 7, 4, 5, 1]],
    riskyIndex: 1,
  },
  {
    title: 'Escasez del proveedor',
    text: 'Habrá escasez. Comprar mucho protege ventas, pero consume caja.',
    topic: 'Inventarios, liquidez, proveedores y negociación.',
    opts: [
      ['Comprar lo necesario', 'Liquidez · crecimiento estable'],
      ['Comprar todo el lote', 'Gran potencial de ventas · presión financiera'],
      ['Negociar crédito', 'Proteges caja mediante negociación'],
    ],
    effects: [[230, 7, 5, 3, 7, 0], [900, 30, 4, 0, -16, 26], [360, 9, 6, 3, 9, 3]],
    riskyIndex: 1,
  },
  {
    title: 'Diferencias contables',
    text: 'El inventario físico no coincide con los registros.',
    topic: 'Control administrativo, auditoría y ética organizacional.',
    opts: [
      ['Ocultarlo', 'Ahorro inmediato · si falla, el golpe es enorme'],
      ['Auditar a fondo', 'Costo inmediato · reduces riesgo'],
      ['Corregir rápido', 'Solución equilibrada · mantienes operación'],
    ],
    effects: [[780, 26, 3, -18, -12, 30], [120, 3, 8, 8, 4, -8], [300, 7, 6, 3, 3, -2]],
    riskyIndex: 0,
  },
  {
    title: 'Un inversionista llama',
    text: 'Ofrece capital para acelerar tu expansión, pero exige resultados.',
    topic: 'Financiamiento, inversión, liquidez y estrategia.',
    opts: [
      ['Crecer con recursos propios', 'Menos riesgo · crecimiento lento'],
      ['Aceptar inversión gradual', 'Capital y crecimiento equilibrados'],
      ['Expansión agresiva', 'Muchísimo capital y crecimiento · obligaciones altas'],
    ],
    effects: [[260, 7, 5, 3, 5, 0], [650, 18, 9, 4, 7, 7], [1250, 38, 12, -4, -16, 32]],
    riskyIndex: 2,
  },
  {
    title: 'El equipo está agotado',
    text: 'La carga de trabajo aumenta. Debes decidir cómo dirigir al personal.',
    topic: 'Motivación, recursos humanos, liderazgo y productividad.',
    opts: [
      ['Invertir en bienestar', 'Menos dinero hoy · satisfacción y confianza'],
      ['Exigir horas extra', 'Producción y dinero rápido · desgaste y riesgo'],
      ['Incentivos por desempeño', 'Pagas por resultados · productividad'],
    ],
    effects: [[100, 2, 9, 4, 3, -4], [850, 27, 18, -10, -12, 26], [420, 12, 14, 2, 0, 5]],
    riskyIndex: 1,
  },
  {
    title: 'Campaña viral',
    text: 'Puedes probar una campaña o apostar fuerte por una campaña masiva.',
    topic: 'Marketing, segmentación, retorno de inversión y estrategia.',
    opts: [
      ['Prueba piloto', 'Menor ganancia · reduces incertidumbre'],
      ['Campaña segmentada', 'Buena relación entre inversión y retorno'],
      ['Campaña masiva', 'Gran ganancia potencial · presión y riesgo altos'],
    ],
    effects: [[180, 6, 5, 5, 3, -1], [450, 13, 8, 6, 2, 5], [1100, 32, 15, 2, -14, 28]],
    riskyIndex: 2,
  },
  {
    title: 'Automatización',
    text: 'Una tecnología puede elevar muchísimo la productividad.',
    topic: 'Innovación, cambio organizacional y productividad.',
    opts: [
      ['Automatizar casi todo', 'Productividad explosiva · resistencia y riesgo'],
      ['Implementación gradual', 'Control y capacitación · crecimiento seguro'],
      ['Solución flexible', 'Equilibrio entre velocidad y adaptación'],
    ],
    effects: [[1350, 40, 24, -8, -14, 32], [220, 7, 12, 4, 4, -3], [480, 14, 15, 4, 4, 3]],
    riskyIndex: 0,
  },
  {
    title: 'La junta directiva final',
    text: 'Debes definir la estrategia que cerrará tu primera etapa empresarial.',
    topic: 'Planeación estratégica, toma de decisiones y control.',
    opts: [
      ['Consolidar', 'Empresa sana · estable y sostenible'],
      ['Expandir con disciplina', 'Crecimiento con riesgo moderado'],
      ['Apostarlo todo', 'Enorme ganancia si tus fundamentos son sólidos'],
    ],
    effects: [[350, 8, 7, 7, 5, 0], [700, 20, 13, 6, 6, 10], [1600, 48, 20, 0, -18, 38]],
    riskyIndex: 2,
  },
  {
    title: 'Fuga de talento',
    text: 'Tu mejor gerente recibe una oferta de la competencia. Ofrece más sueldo.',
    topic: 'Retención de talento, recursos humanos y costos.',
    opts: [
      ['Igualar el sueldo', 'Costo alto · mantienes continuidad'],
      ['Dejarlo ir y reemplazar', 'Ahorro inmediato · productividad cae'],
      ['Promover desde dentro', 'Riesgo de inexperiencia · moral sube'],
    ],
    effects: [[-450, 3, 5, 3, -8, 4], [200, -5, -12, -4, 2, 8], [100, 4, -6, 6, 2, -2]],
    riskyIndex: 2,
  },
  {
    title: 'Auditoría sorpresa',
    text: 'Las autoridades fiscales llegan sin previo aviso. Todo debe estar en orden.',
    topic: 'Cumplimiento, control fiscal y transparencia.',
    opts: [
      ['Cooperar totalmente', 'Tiempo perdido · reduces riesgo legal'],
      ['Negar acceso y pedir orden judicial', 'Ganas tiempo · reputación y riesgo suben'],
      ['Entregar solo lo conveniente', 'Ahorro inmediato · si descubren, multa enorme'],
    ],
    effects: [[-200, -2, -3, 5, -3, -10], [100, 0, 0, -8, 0, 22], [400, 5, 2, -12, 5, 30]],
    riskyIndex: 2,
  },
  {
    title: 'Demanda laboral',
    text: 'Un ex-empleado te demanda por despido injustificado.',
    topic: 'Legal, relaciones laborales y gestión de conflictos.',
    opts: [
      ['Arreglo extrajudicial', 'Costo fijo · cierras el tema rápido'],
      ['Pelear en juicio', 'Riesgo de perder más dinero y reputación'],
      ['Mediación', 'Costo medio · solución intermedia'],
    ],
    effects: [[-600, 0, 0, 3, -5, -5], [200, 0, -2, -10, -2, 25], [-350, 0, 0, 1, -2, 2]],
    riskyIndex: 1,
  },
  {
    title: 'Crisis de producto',
    text: 'Un lote defectuoso llegó al mercado. Hay que decidir cómo reaccionar.',
    topic: 'Calidad, servicio al cliente y reputación.',
    opts: [
      ['Retiro voluntario', 'Costo alto · reputación se recupera'],
      ['Ignorar y esperar quejas', 'Ahorro inmediato · reputación en riesgo'],
      ['Reemplazar silenciosamente', 'Costo medio · evitas escándalo'],
    ],
    effects: [[-550, -2, 3, 8, -4, -8], [300, 0, -3, -18, 3, 28], [-300, 0, 0, 2, 0, 5]],
    riskyIndex: 1,
  },
  {
    title: 'Oportunidad de exportación',
    text: 'Un distribuidor extranjero quiere llevar tu producto a otro país.',
    topic: 'Comercio exterior, expansión y riesgo cambiario.',
    opts: [
      ['Exportar con cautela', 'Ingresos nuevos · riesgo cambiario moderado'],
      ['Rechazar la oferta', 'Seguridad · pierdes crecimiento'],
      ['Vender todo el inventario al exterior', 'Gran ingreso · dependencia y riesgo altos'],
    ],
    effects: [[500, 15, 5, 4, 4, 12], [50, 0, 0, 2, 2, -2], [1200, 30, 0, 2, -10, 28]],
    riskyIndex: 2,
  },
  {
    title: 'Corte de energía',
    text: 'Una falla eléctrica daña equipos y detiene la producción por horas.',
    topic: 'Continuidad operativa, mantenimiento y riesgos operacionales.',
    opts: [
      ['Reparar y reanudar', 'Costo fijo · producción se recupera'],
      ['Comprar generador de respaldo', 'Inversión alta · previene futuras paradas'],
      ['Operar a media máquina', 'Ahorro hoy · pedidos se atrasan'],
    ],
    effects: [[-400, 0, -2, 2, -3, 3], [-800, 2, 5, 3, 5, -10], [100, -3, -8, -5, 0, 15]],
    riskyIndex: 2,
  },
  {
    title: 'Redes sociales negativas',
    text: 'Un cliente insatisfecho hace viral una queja sobre tu empresa.',
    topic: 'Relaciones públicas, comunicación y reputación digital.',
    opts: [
      ['Responder públicamente y compensar', 'Costo inmediato · reputación se recupera'],
      ['Ignorar y esperar que pase', 'Ahorro · reputación sigue cayendo'],
      ['Demandar por difamación', 'Ganas si pruebas · imagen pública empeora'],
    ],
    effects: [[-350, 0, 0, 10, -2, -5], [100, 0, -2, -15, 2, 18], [-200, 0, 0, -8, -3, 25]],
    riskyIndex: 1,
  },
  {
    title: 'Socio fundador se va',
    text: 'Tu socio quiere separarse y llevarse su parte del negocio.',
    topic: 'Asociación, negociación y estructura corporativa.',
    opts: [
      ['Comprar su parte', 'Costo alto · mantienes control total'],
      ['Negociar salida gradual', 'Estabilidad · pagos a plazos'],
      ['Disolver la sociedad', 'Pérdida inmediata · empiezas de nuevo'],
    ],
    effects: [[-900, 5, 3, 4, -10, 5], [-400, 2, 2, 3, -3, 2], [-1200, -10, -8, -5, -8, 20]],
    riskyIndex: 2,
  },
  {
    title: 'Tecnología obsoleta',
    text: 'Tu sistema principal ya no soporta la demanda. Hay que actualizar.',
    topic: 'Innovación tecnológica, inversión y competitividad.',
    opts: [
      ['Actualizar todo de una vez', 'Costo alto · productividad sube mucho'],
      ['Seguir como vamos', 'Ahorro hoy · productividad se estanca'],
      ['Migración por fases', 'Costo repartido · transición lenta'],
    ],
    effects: [[-1000, 10, 20, 5, -8, 8], [100, 0, -5, -2, 2, 12], [-400, 3, 8, 2, 0, 0]],
    riskyIndex: 1,
  },
  {
    title: 'Inflación descontrolada',
    text: 'Los costos de insumos suben de golpe. Tus márgenes desaparecen.',
    topic: 'Economía, finanzas y ajuste de precios.',
    opts: [
      ['Subir precios de inmediato', 'Margen se recupera · clientes se asustan'],
      ['Absorber el costo', 'Mantienes clientes · caja se vacía rápido'],
      ['Renegociar con proveedores', 'Ganas tiempo · no siempre funciona'],
    ],
    effects: [[300, 2, -3, -8, 5, 10], [-200, 0, 0, 4, -12, 6], [100, 0, 2, 2, 3, 15]],
    riskyIndex: 2,
  },
  {
    title: 'Robo interno',
    text: 'Descubres que un empleado ha estado desviando fondos pequeños.',
    topic: 'Control interno, ética y seguridad.',
    opts: [
      ['Despedir y denunciar', 'Justicia · proceso legal largo y costoso'],
      ['Despedir silenciosamente', 'Rápido · sin recuperar dinero, sin escarmiento'],
      ['Confrontar y recuperar', 'Recuperas dinero · riesgo de represalia'],
    ],
    effects: [[-300, 0, -2, 5, -2, 5], [-150, 0, 0, -3, 0, 12], [250, 0, 0, 2, 2, 18]],
    riskyIndex: 2,
  },
  {
    title: 'Nuevo competidor agresivo',
    text: 'Una startup con mucho capital entra a tu mercado ofreciendo todo más barato.',
    topic: 'Estrategia competitiva, posicionamiento y diferenciación.',
    opts: [
      ['Diferenciarte por calidad', 'Inversión en marca · fidelizas clientes'],
      ['Competir en precio', 'Guerra de desgaste · liquidez en riesgo'],
      ['Comprar al competidor', 'Gasto enorme · eliminas la amenaza'],
    ],
    effects: [[-500, 8, 5, 10, -2, 3], [200, 5, -2, -5, -10, 25], [-1500, 25, 8, 5, -12, 15]],
    riskyIndex: 1,
  },
  {
    title: 'Soborno ofrecido',
    text: 'Un funcionario te insinúa que un "regalo" aceleraría tu trámite.',
    topic: 'Ética empresarial, compliance y reputación.',
    opts: [
      ['Rechazar y denunciar', 'Justicia · el trámite se retrasa mucho'],
      ['Aceptar pagar el soborno', 'Trámite rápido · riesgo legal enorme'],
      ['Negociar por vía formal', 'Lento · mantienes tu integridad'],
    ],
    effects: [[-200, 0, -3, 8, -3, -5], [600, 5, 0, -15, 5, 35], [100, 0, 0, 3, 0, 2]],
    riskyIndex: 1,
  },
  {
    title: 'Expansión obligada',
    text: 'Tu local actual ya no da abasto. Debes mudarte o expandirte.',
    topic: 'Crecimiento, inversión inmobiliaria y planeación.',
    opts: [
      ['Abrir segunda sucursal', 'Inversión alta · crecimiento real'],
      ['Mudarte a local más grande', 'Costo de mudanza · interrupción temporal'],
      ['Quederte y operar a saturación', 'Ahorro · pierdes ventas y clientes'],
    ],
    effects: [[-1200, 22, 5, 5, -10, 12], [-800, 10, -3, 3, -5, 8], [200, -5, -8, -6, 3, 15]],
    riskyIndex: 2,
  },
  {
    title: 'Boicot de clientes',
    text: 'Un grupo de clientes organiza un boicot por una declaración pública tuya.',
    topic: 'Comunicación corporativa, imagen pública y crisis.',
    opts: [
      ['Disculparse públicamente', 'Humillación · reduces el daño'],
      ['Mantener la postura', 'Firmeza · pierdes clientes y reputación'],
      ['Contratar firma de PR', 'Costo alto · manejo profesional de crisis'],
    ],
    effects: [[-300, -2, 0, 5, -3, -3], [100, 0, 0, -18, -5, 20], [-700, 0, 0, 8, 0, -5]],
    riskyIndex: 1,
  },
  {
    title: 'Quiebra de cliente principal',
    text: 'Tu cliente más grande se declara en quiebra y te debe mucho dinero.',
    topic: 'Riesgo financiero, concentración de clientes y crédito.',
    opts: [
      ['Diversificar clientela de inmediato', 'Costo de marketing · reduces riesgo futuro'],
      ['Demandar por cobro', 'Proceso largo · recuperas poco o nada'],
      ['Negociar con acreedores', 'Plan de pagos · liquidez exprimida'],
    ],
    effects: [[-600, 8, 3, 3, -5, -3], [-300, 0, -2, -3, -3, 18], [100, 0, 0, 2, -10, 10]],
    riskyIndex: 1,
  },
  {
    title: 'Regulación nueva',
    text: 'El gobierno aprueba una norma que obliga a cambiar tu proceso productivo.',
    topic: 'Cumplimiento normativo, adaptación y costos.',
    opts: [
      ['Adaptar de inmediato', 'Costo alto · evitas multas y cierres'],
      ['Pedir prórroga', 'Ganas tiempo · riesgo de multa crece'],
      ['Ignorar y esperar', 'Ahorro hoy · multa y cierre casi seguro'],
    ],
    effects: [[-800, 3, 5, 5, -5, -5], [100, 0, 0, 0, 2, 15], [200, 0, -3, -5, 3, 35]],
    riskyIndex: 2,
  },
  {
    title: 'Desastre natural',
    text: 'Una inundación daña tu almacén. Pierdes inventario y equipos.',
    topic: 'Gestión de riesgos, seguros y continuidad.',
    opts: [
      ['Reparar con seguro', 'Tiempo de recuperación · cubres la mayoría'],
      ['Reponer sin seguro', 'Costo total · caja se desploma'],
      ['Operar con lo que queda', 'Ahorro · producción y entregas al mínimo'],
    ],
    effects: [[-400, 0, 0, 3, -3, -2], [-1500, -5, -8, -3, -15, 10], [100, -8, -12, -5, 0, 22]],
    riskyIndex: 1,
  },
  {
    title: 'Oferta de adquisición',
    text: 'Una corporación quiere comprar tu empresa. La oferta es tentadora.',
    topic: 'Valoración, negociación y visión a largo plazo.',
    opts: [
      ['Vender la empresa', 'Ganancia personal · el juego termina'],
      ['Rechazar y seguir creciendo', 'Riesgo · mantienes el control'],
      ['Vender el 49% y mantener control', 'Capital fresco · pierdes participación'],
    ],
    effects: [[2000, 0, 0, 0, 20, 0], [300, 10, 5, 3, 3, 8], [1000, 15, 5, 2, 8, 12]],
    riskyIndex: 0,
  },
  {
    title: 'Espionaje industrial',
    text: 'Un competidor copió tu producto estrella. La patente es débil.',
    topic: 'Propiedad intelectual, innovación y ventaja competitiva.',
    opts: [
      ['Demandar por patente', 'Costo legal alto · resultado incierto'],
      ['Lanzar versión mejorada', 'Inversión en I+D · recuperas ventaja'],
      ['Ignorar y bajar precios', 'Guerra de precios · margen desaparece'],
    ],
    effects: [[-700, 0, 0, 3, -3, 15], [-900, 12, 12, 5, -5, 5], [200, 3, -5, -8, -12, 25]],
    riskyIndex: 2,
  },
  {
    title: 'Evaluación final',
    text: 'La junta revisa tu desempeño. Debes justificar por qué mereces quedar entre los 5.',
    topic: 'Evaluación de desempeño, estrategia final y control.',
    opts: [
      ['Mostrar solidez financiera', 'Estabilidad · los fuertes sobreviven'],
      ['Demostrar crecimiento agresivo', 'Impresiona · si es real, pasas'],
      ['Riesgo calculado final', 'Todo o nada · si falla, quedas fuera'],
    ],
    effects: [[400, 10, 8, 8, 6, 0], [600, 18, 10, 5, 3, 12], [1400, 35, 18, -5, -15, 35]],
    riskyIndex: 2,
  },
];
